package ds.token;

public enum TokenType {
    // Data types
    INTEGER, FLOAT, BOOLEAN, STRING, NONE,

    // Operators
    ARITHMETIC_OPERATOR, LOGICAL_OPERATOR, ASSIGNMENT_OPERATOR, COMPARISON_OPERATOR,

    // Reserved words
    BREAK_KEYWORD, RETURN_KEYWORD, END_KEYWORD, IF_KEYWORD, ELSE_KEYWORD, FUNCTION_DECLARATION, VARIABLE_DECLARATION,
    BEGIN_KEYWORD, WHILE_KEYWORD, NEXT_KEYWORD,

    // Miscellaneous
    USER_DEFINED_SYMBOL, NEWLINE, SEPARATOR
}